### ISSUE TITLE
Move to next match with Ctrl+I 

### ISSUE THREAD

**Issue by phw** [Stormherz/atom-incsearch#2]
It would be great if `Ctrl` + `I` would move to the next match, if a search is already started. IMHO that makes the usage so much easier and faster than with separate key bindings.

I have added the following keybindings into my custom config, and this really makes using your package great:
```
'.platform-win32 .incsearch, .platform-linux .incsearch':
  'ctrl-i': 'incsearch:goto:next-match'
  'shift-ctrl-i': 'incsearch:goto:prev-match'

'.platform-darwin .incsearch':
  'cmd-i': 'incsearch:goto:next-match'
  'shift-cmd-i': 'incsearch:goto:prev-match'
```

**Comment by Stormherz** [comment]
@phw sounds good, I'll add this to package in a little while, thanks for the feedback!

**Comment by Stormherz** [comment]
@phw published an update, you can remove custom keybinding configuration now, should work out of the box
